.\" Process this file with
.\" groff -man -Tascii simbur-full.1
.\"
.TH SIMBUR-FULL 1 "APRIL 2013" "Jade Systems Inc" "User Manuals"
.SH NAME
simbur-full \- the SIMple Back Up and Recovery full backup
.br
simbur-incremental \- the SIMple Back Up and Recovery client incremental backup
.SH SYNOPSIS
.B /usr/local/lib/simbur-full 
.br
.B /usr/local/lib/simbur-incremental
.SH DESCRIPTION
.B simbur-full
creates a copy of all files and directories below the BACKUP_SOURCE defined in
.BR client-conf (5).
.B simbur-incremental
creates a copy of all files and directories that have changed since the last
full or incremental backup. The incremental backup is a complete copy 
of all the files and directories below the BACKUP_SOURCE, but only requires
space for the files that have changed.

(
.B simbur-incremental
works by creating a duplicate directory tree using hard links to the previous
backup, then creating new files only for those files that have changed.)

These programs must be run with superuser privileges.
.SH FILES
.I /etc/simbur/client.conf
.RS
The client-side configuration file. See
.BR client.conf (5)
for further details.
.SH BUGS
See the issues log at: https://github.com/lcreid/simbur/issues
.SH AUTHOR
Larry Reid <larry.reid@jadesystems.ca>
.SH "SEE ALSO"
.BR simbur-enroll-client (1),
.BR simburd (1)

