.\" Process this file with
.\" groff -man -Tascii simbur-server.conf.5
.\"
.TH SERVER.CONF 5 "APRIL 2013" "Jade Systems Inc" "User Manuals"
.SH NAME
simbur-server.conf \- the SIMple Back Up and Recovery server configuration file
.SH DESCRIPTION
.B simbur-server.conf
configures the Simbur server programs. It includes the location of the
backup files.

.SH BUGS
See the issues log at: https://github.com/lcreid/simbur/issues
.SH AUTHOR
Larry Reid <larry.reid@jadesystems.ca>
.SH "SEE ALSO"
.BR simbur-enroll-server (1),
.BR simbur-full (1),
.BR simbur-incremental (1),
.BR simbur-server (1),
.BR simburd (1)

